### ISSUE TITLE
RegisterContext pattern not a regular expression?

### ISSUE THREAD

**Issue by LeandroGuillen** [telefonicaid/fiware-SDK#4]
I've seen that you are using a pattern in the example provided in FIWARE-sdk/Javascript/orion/README.md right at the end.

You are using the "\*" character as pattern meaning "all", but this kind of conflicts with the pattern used in the context broker which is ".\*" from regular expressions.

This may be a deliberate decision. I just want to point it out in case it's not.

**Comment by jmcanterafonseca** [comment]
yes, you are right @LeandroGuillen. Fixed
