### ISSUE TITLE
SyntaxError: Use of const in strict mode

### ISSUE THREAD

**Issue by leeprovoost** [telefonicaid/fiware-SDK#5]
The code in the npm lib uses both strict mode and const, which triggers the "SyntaxError: Use of const in strict mode". I can get it working by starting the node server with the -harmony flag, but it doesn't feel right that a third party npm lib enforces this. 

Is there any reasoning behind this? Is there a possibility to change the const to standard vars instead? 

Also, might be worth adding this info to the README file.

**Comment by tania-pets** [comment]
@leeprovoost update your node version.

**Comment by jmcanterafonseca** [comment]
closed, thanks Tania for responding
